In [1]:
import numpy as np

P_y_given_x = np.array([[1,0,0], [0,1,0], [0,0,1]])
P_y_given_x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [3]:
P = np.argmax(P_y_given_x, axis=1)
P

array([0, 1, 2], dtype=int64)

In [21]:
a = np.arange(1,10).reshape((3,3))
print(a)
print(a *a)
print(a.dot(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [18]:
b = a[0,:]
print(b)
print(b *b)
print(b.dot(b))

[1 2 3]
[1 4 9]
14


array([10, 20, 30])