In [1]:
import theano.tensor as T 
import theano 
import numpy as np 

In [3]:
x, y, b = T.dvectors('x', 'y', 'b')

In [6]:
x.T.dot(y)

dot.0

## 感覺一下 : 存量是什麼

In [39]:
y.type

TensorType(float64, vector)

In [38]:
x = T.matrix('x')
y = T.vector('y')
z = x.dot(y)
op = theano.function(
    inputs=[x, y], 
    outputs=z 
)

print('type(x)', type(x))
print('type(z)', type(z))
print('type(op)', type(op))

type(x) <class 'theano.tensor.var.TensorVariable'>
type(z) <class 'theano.tensor.var.TensorVariable'>
type(op) <class 'theano.compile.function_module.Function'>


In [31]:
X = np.arange(12).reshape(4, 3)
y = np.array([0.5, 0.5, 0.5])
Z = op(X, y)
print(Z)
print('type(Z)', type(Z))

[ 1.5  6.  10.5 15. ]
type(Z) <class 'numpy.ndarray'>


## 感覺一下 : shared 是什麼

In [30]:
W = theano.shared(np.random.randn(3, 5), 'W')
print(W.get_value())
print('type(W.get_value())', type(W.get_value()))
print('type(W)', type(W))

[[-0.99159282  1.13600632 -0.18332626  0.54548387 -0.4552968 ]
 [ 0.67004384  1.16371516  0.9982994   0.26454643  0.67614672]
 [ 0.13862037  1.46715598 -1.66128136  1.39699727 -0.54399674]]
type(W.get_value()) <class 'numpy.ndarray'>
type(W) <class 'theano.tensor.sharedvar.TensorSharedVariable'>


In [42]:
b = theano.shared(np.array([100, 100, 100, 100, 100]), 'b')
X = T.matrix('X')
Z = X.dot(W) + b

op2 = theano.function(
    inputs=[X],
    outputs=Z
)

In [43]:
X_test = np.arange(12).reshape(4, 3)
Z_test = op2(X_test)

Z_test

array([[100.94728459, 104.09802712,  97.67573669, 103.05854098,
         99.58815324],
       [100.39849878, 115.3986595 ,  95.13681206, 109.67962371,
         98.61871279],
       [ 99.84971297, 126.69929189,  92.59788743, 116.30070644,
         97.64927234],
       [ 99.30092716, 137.99992427,  90.0589628 , 122.92178917,
         96.67983189]])

## theano setup

In [66]:
import theano
theano.config.floatX = 'float64'
theano.config.floatX = 'float32'

In [67]:
print(theano.config.floatX)

float32


In [6]:
targets = np.array([1, 3, 2, 4])

In [16]:
targets = np.array([1, 3, 2, 4])
pY = np.array([[1,0,0,0], [0,0,1,0], [0,1,0,0], [0,0,0,1]])
pY

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]])

In [37]:
pY[np.arange(pY.shape[0]),  0.6]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [18]:
np.arange(pY.shape[0])

array([0, 1, 2, 3])