In [12]:
import numpy as np 

In [19]:
x = np.arange(12).reshape(4,3)
w = np.arange(15).reshape(3,5)
b = np.array([100,100,100,100,100])
x.dot(w)+ b

array([[125, 128, 131, 134, 137],
       [170, 182, 194, 206, 218],
       [215, 236, 257, 278, 299],
       [260, 290, 320, 350, 380]])

In [22]:
x.mean(axis=0)

array([4.5, 5.5, 6.5])

In [4]:
from theano_ann_bySean import HiddenLayer, ANN

In [9]:
h = HiddenLayer(3, 5, 0)
W_0, b_0 = h.params
W_0.get_value()

array([[-0.05559217, -0.1737677 , -0.02817758, -0.51767826, -0.5420567 ],
       [ 0.05689536, -0.01532626, -0.40573195,  0.03138047, -0.30534428],
       [ 0.63283306, -0.47980568, -0.01201905, -0.19975922, -0.10787011]],
      dtype=float32)

In [13]:
np.zeros_like(W_0.get_value(), dtype=np.float32)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)