In [1]:
import numpy as np
import pandas as pd

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, GRU

In [2]:
T = 8
D = 2
M = 3

X = np.random.randn(1, T, D)

In [3]:
def lstm():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o", o)  # out state 的形狀就是 hidden state 的形狀，而且值一樣
  print("h", h) 
  print("c", c)

In [4]:
lstm()

o [[-0.06414101 -0.20674294  0.02726241]]
h [[-0.06414101 -0.20674294  0.02726241]]
c [[-0.14087166 -0.38450044  0.04022186]]


In [ ]:
def lstm2():
  input_ = Input(shape=(T, D))
  rnn = LSTM(M, return_state=True, return_sequences=True)
  # rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print("o:", o) # (1, 8, 3)
  print("h:", h)
  print("c:", c)

In [ ]:
lstm2()

o: [[[-0.0051235   0.03065772 -0.12945066]
  [-0.10817776  0.1399919   0.1403887 ]
  [-0.05008662  0.13514489 -0.08037736]
  [ 0.22087705  0.01934767 -0.04673928]
  [ 0.2788855  -0.0530927  -0.10502584]
  [ 0.21729593 -0.05539799  0.01199838]
  [ 0.01268141  0.13583557  0.3971529 ]
  [ 0.13679996  0.03363436  0.17904975]]]
h: [[0.13679996 0.03363436 0.17904975]]
c: [[0.22810343 0.05886981 0.6005645 ]]


In [ ]:
def gru1():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)


In [ ]:
gru1()

o: [[ 0.45297378 -0.38774905 -0.26529193]]
h: [[ 0.45297378 -0.38774905 -0.26529193]]


In [ ]:
def gru2():
  input_ = Input(shape=(T, D))
  rnn = GRU(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print("o:", o)
  print("h:", h)

In [ ]:
gru2()

o: [[[-0.22032735 -0.24831197 -0.09967938]
  [-0.06124873  0.06142777  0.12086874]
  [-0.2872342  -0.23290946 -0.0114611 ]
  [-0.08688517 -0.21038276 -0.5612143 ]
  [-0.09483827 -0.29404107 -0.57034856]
  [ 0.15948975  0.0597482   0.13770778]
  [ 0.19608495  0.2939155   0.31741637]
  [ 0.37954518  0.4019193   0.3086524 ]]]
h: [[0.37954518 0.4019193  0.3086524 ]]
