In [1]:
import numpy as np 

pY = np.arange(1,10).reshape(3, 3)
pY

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])


# =======做內積dot運算===========
# 傳統算法
b.dot(pY)

# numpy indexing 形態一 : 取 vector
pY[1]

array([4, 5, 6])

In [17]:
Y_vector = np.array([2, 0, 1])
Y_one_hot = np.array([[0,0,1], [1,0,0], [0,1,0]])
Y_one_hot

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [29]:
# ====矩陣-矩陣對應元素相乘，再取sum()=====
## 算cost function 的公式

# 傳統算法
Y_one_hot*pY

array([[0, 0, 3],
       [4, 0, 0],
       [0, 8, 0]])

In [33]:
# numpy indexing 型態二 : 取元素
pY[[0,1,2], Y_vector]

array([3, 4, 8])

In [5]:
a = np.array([1,1,1,0,0,0])
b = np.array([0,0,1,1,0,0])
print(a == b)
np.mean(a == b)

[False False  True False  True  True]


0.5